In [105]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 255)

In [106]:
PATH = "/Users/pdesadmin/.kaggle/competitions/home-credit-default-risk"

In [107]:
data = pd.read_csv(PATH+"/application_train.csv", nrows=100)
test = pd.read_csv(PATH+"/application_test.csv", nrows=100)

bureau_balance = pd.read_csv(PATH+"/bureau_balance.csv", nrows=100)
bureau = pd.read_csv(PATH+"/bureau.csv", nrows=100)
previous_application = pd.read_csv(PATH+"/previous_application.csv", nrows=100)
credit_card_balance = pd.read_csv(PATH+"/credit_card_balance.csv", nrows=100)
installments_payments = pd.read_csv(PATH+"/installments_payments.csv", nrows=100)
POS_CASH_balance = pd.read_csv(PATH+"/POS_CASH_balance.csv", nrows=100)

In [108]:
data["data_type"] = "train"
test["data_type"] = "test"

In [109]:
data = pd.read_csv(PATH+"/application_train.csv")
data["TARGET"].value_counts()

0    282686
1     24825
Name: TARGET, dtype: int64

In [112]:
def one_hot_encoder(data, nan_as_category = True):
    original_columns = list(data.columns)
    categorical_columns = [col for col in data.columns if data[col].dtype == 'object' and len(data[col].value_counts()) <= 5]
    data = pd.get_dummies(data, columns= categorical_columns, dummy_na= nan_as_category)
    new_columns = [c for c in data.columns if c not in original_columns]

    return data, new_columns

In [113]:
data, new_columns = one_hot_encoder(data)

In [115]:
new_columns

['NAME_CONTRACT_TYPE_Cash loans',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'NAME_CONTRACT_TYPE_nan',
 'CODE_GENDER_F',
 'CODE_GENDER_M',
 'CODE_GENDER_XNA',
 'CODE_GENDER_nan',
 'FLAG_OWN_CAR_N',
 'FLAG_OWN_CAR_Y',
 'FLAG_OWN_CAR_nan',
 'FLAG_OWN_REALTY_N',
 'FLAG_OWN_REALTY_Y',
 'FLAG_OWN_REALTY_nan',
 'NAME_EDUCATION_TYPE_Academic degree',
 'NAME_EDUCATION_TYPE_Higher education',
 'NAME_EDUCATION_TYPE_Incomplete higher',
 'NAME_EDUCATION_TYPE_Lower secondary',
 'NAME_EDUCATION_TYPE_Secondary / secondary special',
 'NAME_EDUCATION_TYPE_nan',
 'FONDKAPREMONT_MODE_not specified',
 'FONDKAPREMONT_MODE_org spec account',
 'FONDKAPREMONT_MODE_reg oper account',
 'FONDKAPREMONT_MODE_reg oper spec account',
 'FONDKAPREMONT_MODE_nan',
 'HOUSETYPE_MODE_block of flats',
 'HOUSETYPE_MODE_specific housing',
 'HOUSETYPE_MODE_terraced house',
 'HOUSETYPE_MODE_nan',
 'EMERGENCYSTATE_MODE_No',
 'EMERGENCYSTATE_MODE_Yes',
 'EMERGENCYSTATE_MODE_nan']

In [8]:
data["NAME_CONTRACT_TYPE"], i = pd.factorize(data["NAME_CONTRACT_TYPE"])

In [10]:
def feature_engineering(self, data, prefix, skip_columns):
    categorical_feats = []
    numeric_feats     = []
    for f in data.columns:
        if f in skip_columns: continue
        if data[f].dtype == "object":
            categorical_feats.append(f)
        else:
            numeric_feats.append(f)

    for f_ in categorical_feats:
        data[f_], indexer = pd.factorize(data[f_])

    return data

In [57]:
mean_data = data.groupby(["SK_ID_CURR"]).mean()
data.merge(right=mean_data.reset_index(), how="left", on=["SK_ID_CURR"], suffixes=("", "_avg_application"))

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18_avg_application,FLAG_DOCUMENT_19_avg_application,FLAG_DOCUMENT_20_avg_application,FLAG_DOCUMENT_21_avg_application,AMT_REQ_CREDIT_BUREAU_HOUR_avg_application,AMT_REQ_CREDIT_BUREAU_DAY_avg_application,AMT_REQ_CREDIT_BUREAU_WEEK_avg_application,AMT_REQ_CREDIT_BUREAU_MON_avg_application,AMT_REQ_CREDIT_BUREAU_QRT_avg_application,AMT_REQ_CREDIT_BUREAU_YEAR_avg_application
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,100082,0,Cash loans,M,N,N,2,180000.000,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
71,100083,0,Cash loans,M,Y,Y,0,103500.000,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
72,100084,0,Cash loans,M,N,Y,2,225000.000,495351.0,26140.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
73,100085,0,Cash loans,M,N,Y,1,157500.000,755190.0,28894.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
74,100086,0,Cash loans,F,N,Y,1,135000.000,675000.0,21775.5,...,0,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0
75,100087,0,Cash loans,F,N,Y,1,202500.000,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
76,100088,0,Revolving loans,F,N,N,0,112500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
77,100089,0,Cash loans,M,N,Y,0,135000.000,337761.0,15781.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
78,100093,0,Cash loans,F,N,Y,1,94500.000,585000.0,28273.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
79,100094,0,Cash loans,F,N,Y,0,108000.000,113760.0,5301.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80,100095,0,Revolving loans,F,N,Y,2,67500.000,135000.0,6750.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
81,100096,1,Cash loans,F,N,Y,0,81000.000,252000.0,14593.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
82,100097,0,Cash loans,M,Y,Y,0,157500.000,760225.5,30280.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
83,100098,0,Revolving loans,M,Y,N,0,225000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
84,100099,0,Cash loans,F,N,Y,0,360000.000,733315.5,41076.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
85,100100,0,Cash loans,M,Y,Y,2,202500.000,796396.5,38443.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
86,100101,0,Cash loans,F,Y,Y,0,202500.000,343377.0,22072.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
87,100102,0,Cash loans,F,N,N,1,126000.000,327024.0,10264.5,...,0,0,0,0,0.0,0.0,0.0,6.0,0.0,0.0
88,100103,0,Cash loans,F,N,Y,0,72000.000,450000.0,16965.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
89,100104,0,Cash loans,F,N,Y,0,90000.000,547344.0,30690.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
90,100105,0,Cash loans,F,N,Y,0,193500.000,225000.0,23755.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
91,100108,0,Cash loans,F,N,Y,3,171000.000,545040.0,31288.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
92,100110,0,Cash loans,M,Y,Y,3,135000.000,373140.0,25065.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
93,100111,0,Cash loans,F,Y,N,1,112500.000,862560.0,27954.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
94,100112,1,Cash loans,M,Y,Y,0,315000.000,953460.0,64107.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
95,100113,0,Cash loans,M,Y,N,0,76500.000,135000.0,6696.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
96,100114,0,Cash loans,F,N,Y,0,135000.000,284400.0,22599.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
97,100115,0,Cash loans,F,N,N,0,90000.000,315000.0,14683.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
98,100116,0,Cash loans,F,N,Y,0,243000.000,900000.0,32017.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
99,100118,0,Cash loans,F,N,Y,0,90000.000,675000.0,26541.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
data.drop("TARGET", axis=1)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,data_type
0,100002,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,351000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
1,100003,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,1129500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
2,100004,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,135000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
3,100006,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,297000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
4,100007,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,513000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
5,100008,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,454500.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,train
6,100009,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,1395000.0,...,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0,train
7,100010,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,1530000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
8,100011,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,913500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
9,100012,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,405000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
10,100014,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,652500.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,train
11,100015,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,135000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
12,100016,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,67500.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,train
13,100017,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,697500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
14,100018,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,679500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
15,100019,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,247500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
16,100020,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,387000.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,train
17,100021,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,270000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
18,100022,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,157500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
19,100023,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,454500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
20,100024,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,427500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
21,100025,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,927000.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0,train
22,100026,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,450000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,train
23,100027,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,225000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
24,100029,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,247500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
25,100030,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,225000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
26,100031,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,702000.0,...,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0,train
27,100032,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,270000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
28,100033,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,675000.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,train
29,100034,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,180000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,100082,Cash loans,M,N,N,2,180000.000,450000.0,21109.5,450000.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0,train
71,100083,Cash loans,M,Y,Y,0,103500.000,573628.5,24435.0,463500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
72,100084,Cash loans,M,N,Y,2,225000.000,495351.0,26140.5,459000.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,train
73,100085,Cash loans,M,N,Y,1,157500.000,755190.0,28894.5,675000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
74,100086,Cash loans,F,N,Y,1,135000.000,675000.0,21775.5,675000.0,...,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0,train
75,100087,Cash loans,F,N,Y,1,202500.000,1288350.0,37800.0,1125000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
76,100088,Revolving loans,F,N,N,0,112500.000,135000.0,6750.0,135000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
77,100089,Cash loans,M,N,Y,0,135000.000,337761.0,15781.5,256500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
78,100093,Cash loans,F,N,Y,1,94500.000,585000.0,28273.5,585000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
79,100094,Cash loans,F,N,Y,0,108000.000,113760.0,5301.0,90000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
80,100095,Revolving loans,F,N,Y,2,67500.000,135000.0,6750.0,135000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
81,100096,Cash loans,F,N,Y,0,81000.000,252000.0,14593.5,252000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
82,100097,Cash loans,M,Y,Y,0,157500.000,760225.5,30280.5,679500.0,...,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,train
83,100098,Revolving loans,M,Y,N,0,225000.000,270000.0,13500.0,270000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
84,100099,Cash loans,F,N,Y,0,360000.000,733315.5,41076.0,679500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
85,100100,Cash loans,M,Y,Y,2,202500.000,796396.5,38443.5,643500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
86,100101,Cash loans,F,Y,Y,0,202500.000,343377.0,22072.5,283500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
87,100102,Cash loans,F,N,N,1,126000.000,327024.0,10264.5,270000.0,...,0,0,0,0.0,0.0,0.0,6.0,0.0,0.0,train
88,100103,Cash loans,F,N,Y,0,72000.000,450000.0,16965.0,450000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
89,100104,Cash loans,F,N,Y,0,90000.000,547344.0,30690.0,472500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
90,100105,Cash loans,F,N,Y,0,193500.000,225000.0,23755.5,225000.0,...,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0,train
91,100108,Cash loans,F,N,Y,3,171000.000,545040.0,31288.5,450000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
92,100110,Cash loans,M,Y,Y,3,135000.000,373140.0,25065.0,337500.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0,train
93,100111,Cash loans,F,Y,N,1,112500.000,862560.0,27954.0,720000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
94,100112,Cash loans,M,Y,Y,0,315000.000,953460.0,64107.0,900000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
95,100113,Cash loans,M,Y,N,0,76500.000,135000.0,6696.0,135000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
96,100114,Cash loans,F,N,Y,0,135000.000,284400.0,22599.0,225000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
97,100115,Cash loans,F,N,N,0,90000.000,315000.0,14683.5,315000.0,...,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0,train
98,100116,Cash loans,F,N,Y,0,243000.000,900000.0,32017.5,900000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
99,100118,Cash loans,F,N,Y,0,90000.000,675000.0,26541.0,675000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train

In [44]:
data["hoge"] = mean_data["AMT_CREDIT"].values

In [49]:
data

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,data_type
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,train
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0,train
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,train
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,train
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,train
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0,train
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,train
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0,train
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,train
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,100082,0,Cash loans,M,N,N,2,180000.000,450000.0,21109.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0,train
71,100083,0,Cash loans,M,Y,Y,0,103500.000,573628.5,24435.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
72,100084,0,Cash loans,M,N,Y,2,225000.000,495351.0,26140.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,train
73,100085,0,Cash loans,M,N,Y,1,157500.000,755190.0,28894.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
74,100086,0,Cash loans,F,N,Y,1,135000.000,675000.0,21775.5,...,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0,train
75,100087,0,Cash loans,F,N,Y,1,202500.000,1288350.0,37800.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
76,100088,0,Revolving loans,F,N,N,0,112500.000,135000.0,6750.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
77,100089,0,Cash loans,M,N,Y,0,135000.000,337761.0,15781.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
78,100093,0,Cash loans,F,N,Y,1,94500.000,585000.0,28273.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
79,100094,0,Cash loans,F,N,Y,0,108000.000,113760.0,5301.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
80,100095,0,Revolving loans,F,N,Y,2,67500.000,135000.0,6750.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
81,100096,1,Cash loans,F,N,Y,0,81000.000,252000.0,14593.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
82,100097,0,Cash loans,M,Y,Y,0,157500.000,760225.5,30280.5,...,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,train
83,100098,0,Revolving loans,M,Y,N,0,225000.000,270000.0,13500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
84,100099,0,Cash loans,F,N,Y,0,360000.000,733315.5,41076.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,train
85,100100,0,Cash loans,M,Y,Y,2,202500.000,796396.5,38443.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
86,100101,0,Cash loans,F,Y,Y,0,202500.000,343377.0,22072.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train
87,100102,0,Cash loans,F,N,N,1,126000.000,327024.0,10264.5,...,0,0,0,0.0,0.0,0.0,6.0,0.0,0.0,train
88,100103,0,Cash loans,F,N,Y,0,72000.000,450000.0,16965.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
89,100104,0,Cash loans,F,N,Y,0,90000.000,547344.0,30690.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,train
90,100105,0,Cash loans,F,N,Y,0,193500.000,225000.0,23755.5,...,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0,train
91,100108,0,Cash loans,F,N,Y,3,171000.000,545040.0,31288.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
92,100110,0,Cash loans,M,Y,Y,3,135000.000,373140.0,25065.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0,train
93,100111,0,Cash loans,F,Y,N,1,112500.000,862560.0,27954.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
94,100112,1,Cash loans,M,Y,Y,0,315000.000,953460.0,64107.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
95,100113,0,Cash loans,M,Y,N,0,76500.000,135000.0,6696.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
96,100114,0,Cash loans,F,N,Y,0,135000.000,284400.0,22599.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,train
97,100115,0,Cash loans,F,N,N,0,90000.000,315000.0,14683.5,...,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0,train
98,100116,0,Cash loans,F,N,Y,0,243000.000,900000.0,32017.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,train
99,100118,0,Cash loans,F,N,Y,0,90000.000,675000.0,26541.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,train

In [27]:
avg_data = data.groupby("SK_ID_CURR").mean()
avg_data.columns = ["avg_"+"application_" + f_ for f_ in avg_data.columns]

In [31]:
avg_data

,avg_application_AMT_ANNUITY,avg_application_AMT_CREDIT,avg_application_AMT_GOODS_PRICE,avg_application_AMT_INCOME_TOTAL,avg_application_AMT_REQ_CREDIT_BUREAU_DAY,avg_application_AMT_REQ_CREDIT_BUREAU_HOUR,avg_application_AMT_REQ_CREDIT_BUREAU_MON,avg_application_AMT_REQ_CREDIT_BUREAU_QRT,avg_application_AMT_REQ_CREDIT_BUREAU_WEEK,avg_application_AMT_REQ_CREDIT_BUREAU_YEAR,...,avg_application_REG_REGION_NOT_LIVE_REGION,avg_application_REG_REGION_NOT_WORK_REGION,avg_application_TARGET,avg_application_TOTALAREA_MODE,avg_application_YEARS_BEGINEXPLUATATION_AVG,avg_application_YEARS_BEGINEXPLUATATION_MEDI,avg_application_YEARS_BEGINEXPLUATATION_MODE,avg_application_YEARS_BUILD_AVG,avg_application_YEARS_BUILD_MEDI,avg_application_YEARS_BUILD_MODE
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,20560.5,568800.0,450000.0,135000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,NaN,0.0392,0.9732,0.9732,0.9732,NaN,NaN,NaN
100002,24700.5,406597.5,351000.0,202500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,1.0,0.0149,0.9722,0.9722,0.9722,0.6192,0.6243,0.6341
100003,35698.5,1293502.5,1129500.0,270000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0714,0.9851,0.9851,0.9851,0.7960,0.7987,0.8040
100004,6750.0,135000.0,135000.0,67500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100005,17370.0,222768.0,180000.0,99000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100006,29686.5,312682.5,297000.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100007,21865.5,513000.0,513000.0,121500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100008,27517.5,490495.5,454500.0,99000.000,0.0,0.0,0.0,1.0,0.0,1.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100009,41301.0,1560726.0,1395000.0,171000.000,0.0,0.0,1.0,1.0,0.0,2.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100010,42075.0,1530000.0,1530000.0,360000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100011,33826.5,1019610.0,913500.0,112500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100012,20250.0,405000.0,405000.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100013,69777.0,663264.0,630000.0,202500.000,0.0,0.0,0.0,1.0,0.0,4.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100014,21177.0,652500.0,652500.0,112500.000,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100015,10678.5,148365.0,135000.0,38419.155,0.0,0.0,0.0,0.0,0.0,2.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100016,5881.5,80865.0,67500.0,67500.000,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0.0,0.0612,0.9811,0.9811,0.9811,NaN,NaN,NaN
100017,28966.5,918468.0,697500.0,225000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0.0,0.1417,0.9806,0.9806,0.9806,0.7348,0.7383,0.7452
100018,32778.0,773680.5,679500.0,189000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0.0,0.3811,0.9985,0.9985,0.9985,0.9796,0.9799,0.9804
100019,20160.0,299772.0,247500.0,157500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100020,26149.5,509602.5,387000.0,108000.000,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100021,13500.0,270000.0,270000.0,81000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100022,7875.0,157500.0,157500.0,112500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0238,0.9881,0.9881,0.9881,0.8368,0.8390,0.8432
100023,17563.5,544491.0,454500.0,90000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100024,21375.0,427500.0,427500.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0530,0.9781,0.9781,0.9782,0.7008,0.7048,0.7125
100025,37561.5,1132573.5,927000.0,202500.000,0.0,0.0,0.0,1.0,0.0,4.0,...,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100026,32521.5,497520.0,450000.0,450000.000,0.0,0.0,0.0,0.0,0.0,5.0,...,0,0,0.0,0.0696,0.9786,0.9786,0.9786,0.7076,0.7115,0.7190
100027,23850.0,239850.0,225000.0,83250.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0,0,0.0,0.1640,0.9876,0.9876,0.9876,0.8300,0.8323,0.8367
100028,49018.5,1575000.0,1575000.0,315000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0,0,NaN,0.3700,0.9970,0.9970,0.9970,0.9592,0.9597,0.9608
100029,12703.5,247500.0,247500.0,135000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0967,0.9861,0.9861,0.9861,0.8096,0.8121,0.8171
100030,11074.5,225000.0,225000.0,90000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0533,0.9781,0.9781,0.9782,0.7008,0.7048,0.7125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100551,31788.0,981360.0,720000.0,144000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100552,32170.5,269982.0,238500.0,180000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100553,10278.0,165915.0,126000.0,126000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,NaN,0.2713,0.9851,0.9851,0.9851,0.7756,0.7786,0.7844
100561,8140.5,67500.0,67500.0,180000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,0,0,NaN,0.1522,0.9866,0.9866,0.9866,0.8164,0.8189,0.8236
100568,24709.5,312768.0,270000.0,112500.000,0.0,0.0,0.0,2.0,0.0,2.0,...,0,0,NaN,0.0674,0.9871,0.9871,0.9871,0.8232,0.8256,0.8301
100569,42174.0,400392.0,360000.0,225000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100591,26077.5,328405.5,283500.0,180000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100592,30006.0,831730.5,702000.0,180000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,NaN,0.0990,0.9945,0.9945,0.9945,0.9252,0.9262,0.9281
100602,23008.5,450000.0,450000.0,99000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100607,23107.5,450000.0,450000.0,135000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0,0,NaN,0.0785,0.9806,0.9806,0.9757,NaN,NaN,NaN
100613,24525.0,526491.0,454500.0,45000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100617,24696.0,481176.0,360000.0,202500.000,0.0,0.0,0.0,1.0,0.0,2.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100618,39924.0,781920.0,675000.0,202500.000,0.0,0.0,0.0,1.0,0.0,6.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100622,9058.5,111384.0,90000.0,67500.000,0.0,0.0,0.0,2.0,0.0,3.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100625,32400.0,735579.0,585000.0,112500.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100677,22459.5,402214.5,328500.0,252000.000,0.0,0.0,0.0,1.0,0.0,2.0,...,0,0,NaN,0.0418,0.9692,0.9692,0.9692,0.5784,0.5840,0.5949
100699,23134.5,323460.0,270000.0,225000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0,0,NaN,0.0858,0.9816,0.9816,0.9816,0.7484,0.7518,0.7583
100702,25015.5,315000.0,315000.0,175500.000,0.0,0.0,0.0,0.0,0.0,4.0,...,0,0,NaN,0.0319,0.9742,0.9742,0.9742,NaN,NaN,NaN
100711,63085.5,1525482.0,1363500.0,180000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,NaN,0.0651,0.9786,0.9786,0.9782,0.7212,0.7249,0.7321
100729,14220.0,180000.0,180000.0,112500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100740,21559.5,296280.0,225000.0,67500.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100744,17905.5,225000.0,225000.0,144000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100745,29034.0,900000.0,900000.0,135000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100747,54769.5,691551.0,625500.0,495000.000,0.0,0.0,0.0,4.0,0.0,0.0,...,0,0,NaN,0.1245,0.9866,0.9866,0.9866,0.8164,0.8189,0.8236
100751,14517.0,450000.0,450000.0,67500.000,0.0,0.0,0.0,1.0,0.0,1.0,...,0,0,NaN,0.0163,0.9781,0.9781,0.9782,0.7008,0.7048,0.7125
100752,27229.5,675000.0,675000.0,135000.000,0.0,0.0,0.0,1.0,0.0,3.0,...,0,0,NaN,0.0645,0.9757,0.9757,0.9757,0.6668,0.6713,0.6798
100753,18688.5,156384.0,135000.0,180000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100754,13221.0,364500.0,364500.0,135000.000,0.0,0.0,0.0,1.0,0.0,2.0,...,0,0,NaN,0.1486,0.9871,0.9871,0.9871,0.8232,0.8256,0.8301
100760,22297.5,224149.5,193500.0,90000.000,0.0,0.0,0.0,0.0,0.0,4.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100762,20637.0,225000.0,225000.0,180000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,TOTALAREA_MODE,WALLSMATERIAL_MODE,WEEKDAY_APPR_PROCESS_START,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_AVG,YEARS_BUILD_MEDI,YEARS_BUILD_MODE,data_type
0,20560.5,568800.0,450000.0,135000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0392,"Stone, brick",TUESDAY,0.9732,0.9732,0.9732,NaN,NaN,NaN,test

In [23]:
data

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,TOTALAREA_MODE,WALLSMATERIAL_MODE,WEEKDAY_APPR_PROCESS_START,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_AVG,YEARS_BUILD_MEDI,YEARS_BUILD_MODE,data_type
0,24700.5,406597.5,351000.0,202500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0149,"Stone, brick",WEDNESDAY,0.9722,0.9722,0.9722,0.6192,0.6243,0.6341,train
1,35698.5,1293502.5,1129500.0,270000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0714,Block,MONDAY,0.9851,0.9851,0.9851,0.7960,0.7987,0.8040,train
2,6750.0,135000.0,135000.0,67500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
3,29686.5,312682.5,297000.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,WEDNESDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
4,21865.5,513000.0,513000.0,121500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,THURSDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
5,27517.5,490495.5,454500.0,99000.000,0.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,WEDNESDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
6,41301.0,1560726.0,1395000.0,171000.000,0.0,0.0,1.0,1.0,0.0,2.0,...,NaN,NaN,SUNDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
7,42075.0,1530000.0,1530000.0,360000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
8,33826.5,1019610.0,913500.0,112500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,WEDNESDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
9,20250.0,405000.0,405000.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,THURSDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
10,21177.0,652500.0,652500.0,112500.000,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,SATURDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
11,10678.5,148365.0,135000.0,38419.155,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,FRIDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
12,5881.5,80865.0,67500.0,67500.000,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0612,NaN,FRIDAY,0.9811,0.9811,0.9811,NaN,NaN,NaN,train
13,28966.5,918468.0,697500.0,225000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0.1417,Panel,THURSDAY,0.9806,0.9806,0.9806,0.7348,0.7383,0.7452,train
14,32778.0,773680.5,679500.0,189000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.3811,Panel,MONDAY,0.9985,0.9985,0.9985,0.9796,0.9799,0.9804,train
15,20160.0,299772.0,247500.0,157500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,SATURDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
16,26149.5,509602.5,387000.0,108000.000,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,THURSDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
17,13500.0,270000.0,270000.0,81000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
18,7875.0,157500.0,157500.0,112500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0238,"Stone, brick",FRIDAY,0.9881,0.9881,0.9881,0.8368,0.8390,0.8432,train
19,17563.5,544491.0,454500.0,90000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
20,21375.0,427500.0,427500.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0530,"Stone, brick",FRIDAY,0.9781,0.9781,0.9782,0.7008,0.7048,0.7125,train
21,37561.5,1132573.5,927000.0,202500.000,0.0,0.0,0.0,1.0,0.0,4.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
22,32521.5,497520.0,450000.0,450000.000,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0696,Panel,THURSDAY,0.9786,0.9786,0.9786,0.7076,0.7115,0.7190,train
23,23850.0,239850.0,225000.0,83250.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0.1640,Mixed,FRIDAY,0.9876,0.9876,0.9876,0.8300,0.8323,0.8367,train
24,12703.5,247500.0,247500.0,135000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0967,Panel,THURSDAY,0.9861,0.9861,0.9861,0.8096,0.8121,0.8171,train
25,11074.5,225000.0,225000.0,90000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0533,"Stone, brick",SATURDAY,0.9781,0.9781,0.9782,0.7008,0.7048,0.7125,train
26,27076.5,979992.0,702000.0,112500.000,0.0,0.0,0.0,2.0,0.0,2.0,...,0.0085,Wooden,MONDAY,0.9732,0.9732,0.9732,NaN,NaN,NaN,train
27,23827.5,327024.0,270000.0,112500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,SATURDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
28,57676.5,790830.0,675000.0,270000.000,0.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,WEDNESDAY,NaN,NaN,NaN,NaN,NaN,NaN,train
29,9000.0,180000.0,180000.0,90000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.1227,Panel,TUESDAY,0.9831,0.9831,0.9831,0.7688,0.7719,0.7779,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,31788.0,981360.0,720000.0,144000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,THURSDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
71,32170.5,269982.0,238500.0,180000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,NaN,NaN,FRIDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
72,10278.0,165915.0,126000.0,126000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.2713,Mixed,TUESDAY,0.9851,0.9851,0.9851,0.7756,0.7786,0.7844,test
73,8140.5,67500.0,67500.0,180000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,0.1522,Panel,FRIDAY,0.9866,0.9866,0.9866,0.8164,0.8189,0.8236,test
74,24709.5,312768.0,270000.0,112500.000,0.0,0.0,0.0,2.0,0.0,2.0,...,0.0674,"Stone, brick",FRIDAY,0.9871,0.9871,0.9871,0.8232,0.8256,0.8301,test
75,42174.0,400392.0,360000.0,225000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
76,26077.5,328405.5,283500.0,180000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
77,30006.0,831730.5,702000.0,180000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0990,Panel,MONDAY,0.9945,0.9945,0.9945,0.9252,0.9262,0.9281,test
78,23008.5,450000.0,450000.0,99000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
79,23107.5,450000.0,450000.0,135000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0785,"Stone, brick",MONDAY,0.9806,0.9806,0.9757,NaN,NaN,NaN,test
80,24525.0,526491.0,454500.0,45000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,WEDNESDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
81,24696.0,481176.0,360000.0,202500.000,0.0,0.0,0.0,1.0,0.0,2.0,...,NaN,NaN,FRIDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
82,39924.0,781920.0,675000.0,202500.000,0.0,0.0,0.0,1.0,0.0,6.0,...,NaN,NaN,WEDNESDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
83,9058.5,111384.0,90000.0,67500.000,0.0,0.0,0.0,2.0,0.0,3.0,...,NaN,NaN,FRIDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
84,32400.0,735579.0,585000.0,112500.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,THURSDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
85,22459.5,402214.5,328500.0,252000.000,0.0,0.0,0.0,1.0,0.0,2.0,...,0.0418,"Stone, brick",THURSDAY,0.9692,0.9692,0.9692,0.5784,0.5840,0.5949,test
86,23134.5,323460.0,270000.0,225000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0858,Panel,WEDNESDAY,0.9816,0.9816,0.9816,0.7484,0.7518,0.7583,test
87,25015.5,315000.0,315000.0,175500.000,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0319,"Stone, brick",MONDAY,0.9742,0.9742,0.9742,NaN,NaN,NaN,test
88,63085.5,1525482.0,1363500.0,180000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0651,"Stone, brick",MONDAY,0.9786,0.9786,0.9782,0.7212,0.7249,0.7321,test
89,14220.0,180000.0,180000.0,112500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
90,21559.5,296280.0,225000.0,67500.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,SUNDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
91,17905.5,225000.0,225000.0,144000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
92,29034.0,900000.0,900000.0,135000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
93,54769.5,691551.0,625500.0,495000.000,0.0,0.0,0.0,4.0,0.0,0.0,...,0.1245,"Stone, brick",THURSDAY,0.9866,0.9866,0.9866,0.8164,0.8189,0.8236,test
94,14517.0,450000.0,450000.0,67500.000,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0163,"Stone, brick",SATURDAY,0.9781,0.9781,0.9782,0.7008,0.7048,0.7125,test
95,27229.5,675000.0,675000.0,135000.000,0.0,0.0,0.0,1.0,0.0,3.0,...,0.0645,Panel,FRIDAY,0.9757,0.9757,0.9757,0.6668,0.6713,0.6798,test
96,18688.5,156384.0,135000.0,180000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,FRIDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
97,13221.0,364500.0,364500.0,135000.000,0.0,0.0,0.0,1.0,0.0,2.0,...,0.1486,Panel,FRIDAY,0.9871,0.9871,0.9871,0.8232,0.8256,0.8301,test
98,22297.5,224149.5,193500.0,90000.000,0.0,0.0,0.0,0.0,0.0,4.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test
99,20637.0,225000.0,225000.0,180000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,MONDAY,NaN,NaN,NaN,NaN,NaN,NaN,test